---
dataset_id:
  type: 'String'
  required: true
  help: 'Dataset identifier'
output_dir:
  type: 'Path'
  mode: 'w'
  required: true
  help: 'Absolute path to output directory'
mt_ref_genome_dir:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Absolute path to directory with mtDNA reference genome'
  default: '/hot/ref/mitochondria_ref/genome_fasta/'
gmapdb:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Directory to gmapdb genomic index files'
  default: '/hot/ref/mitochondria_ref/gmapdb/gmapdb_2021-03-08'
save_intermediate_files:
  type: 'Bool'
  required: true
  default: false
  help: 'Boolean value to indicate whether or not to save intermediate files'
cache_intermediate_pipeline_steps:
  type: 'Bool'
  required: true
  default: false
  help: 'Boolean value to indicate whether or not to cache intermediate pipeline steps'
base_resource_update:
  type: 'ResourceUpdateNamespace'
  required: false
  help: 'User-defined modifications for adjusting base resource allocations for processes'
  elements:
    memory:
      type: 'ResourceUpdateList'
      required: false
      help: 'List of memory updates'
    cpus:
      type: 'ResourceUpdateList'
      required: false
      help: 'List of CPU updates'
patient_id:
  type: 'String'
  required: true
  help: 'Patient identifier'
input:
  type: 'InputBAMNamespace'
  required: true
  help: 'Input samples'
  elements:
    normal:
      type: 'Namespace'
      required: false
      help: 'normal sample id and absolute path to BAM'
      elements:
        sample_id:
          type: 'String'
          required: false
          help: 'data sample identifier'
        data:
          type: 'Path'
          mode: 'r'
          required: false
          help: 'Absolute path to normal sample BAM/CRAM'
    tumor:
      type: 'Namespace'
      required: false
      help: 'tumor sample id and absolute path to BAM'
      elements:
        sample_id:
          type: 'String'
          required: false
          help: 'data sample identifier'
        data:
          type: 'Path'
          mode: 'r'
          required: false
          help: 'Absolute path to tumor sample BAM/CRAM'
