---
dataset_id:
  type: 'String'
  required: true
  help: 'Dataset identifier'
output_dir:
  type: 'Path'
  mode: 'w'
  required: true
  help:  'Absolute path to output directory'
mt_ref_genome_dir:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Absolute path to directory with mtDNA reference genome'
  default: '/hot/ref/mitochondria_ref/gmapdb/gmapdb_2021-03-08'
gmapdb:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Directory to gmapdb genomic index files'
  default: '/hot/ref/mitochondria_ref/gmapdb/gmapdb_2021-03-08'
save_intermediate_files:
  type: 'Bool'
  required: false
  default: false
  help: 'Boolean value to indicate whether or not to save intermediate files'
cache_intermediate_pipeline_steps:
  type: 'Bool'
  required: false
  default: false
  help: 'Boolean value to indicate whether or not to cache intermediate pipeline steps'
patient_id:
  type: 'String'
  required: true
  help: 'Patient identifier'
input:
  type: 'InputBAMNamespace'
  required: true
  help: 'Input samples'
  elements:
    normal:
      type: 'Namespace'
      required: false
      help: 'normal sample id and absolute path to BAM'
      elements:
        id:
          type: 'String'
          required: true
          help: 'Normal sample ID'
        BAM:
          type: 'Path'
          mode: 'r'
          required: true
          help: 'Absolute path to normal sample BAM'
    tumor:
      type: 'Namespace'
      required: false
      help: 'tumor sample id and absolute path to BAM'
      elements:
        id:
          type: 'String'
          required: true
          help: 'Tumor sample ID'
        BAM:
          type: 'Path'
          mode: 'r'
          required: true
          help: 'Absolute path to tumor sample BAM'