@startuml
skinparam SwimlaneTitleFontStyle bold


:==Input Validation
----
Validate the input BAM and corresponding index file;
:==BAMQL
----
Extract mitochondrial reads;
:==MToolBox
----
Align to mitochondrial genome;
if (downsampling enabled) then (yes)
  :==downsample_BAM_Picard
  ----
  downsample BAM;
else (no)
endif
:==MitoCaller
----
Call mitochondrial variants;
:==MitoCaller2VCF
----
Convert results to VCF;
if (paired sample) then (yes)
  :==Call_Heteroplasmy
  ----
  Extract heteroplasmy scores;
else (no)
endif
:==Output Validation
----
Validate output VCF files;

@enduml
