---
name: CICD-base2

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  CICD-base:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      # Checkout codebase
      - name: Checkout
        uses: actions/checkout@v2

      # Run CICD-base
      - name: CICD-base
        uses: docker://blcdsdockerregistry/cicd-base:latest
