---
name: CICD-base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CICD-base:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CICD-base
        uses: docker://ghcr.io/uclahs-cds/cicd-base:latest
